# create your drupal and postgres config here, based off the last assignment
version: '3'

services:
  drupal:
   image: drupal
   ports:
   - "8080:80"
   container_name: drupal
   volumes: 
   - drupal-modules:/var/www/html/modules
   - drupal-profiles:/var/www/html/profiles
   - drupal-sites:/var/www/html/sites
   - drupal-themes:/var/www/html/themes
  mysql:
   image: mysql
   ports: 
   - "3306:3306"
   container_name: mysql
   environment: 
   - MYSQL_ROOT_PASSWORD=pass

  phpmyadmin:
   image: phpmyadmin/phpmyadmin
   container_name: myadmin 
   restart: always
   environment:
   - PMA_ARBITRARY=1
   ports: 
   - "200:80"
   volumes:
   - /sessions
volumes: 
   drupal-modules:
   drupal-profiles:
   drupal-sites:
   drupal-themes:
   sessions: